- name: Disable default NodeJS Version Module
  ansible.builtin.shell: dnf module disable nodejs -y


- name: Enable NodeJS module for V20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Adding Application User
  ansible.builtin.user:
    name: expense

- name: clean the old content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create new directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
    dest: /app
    remote_src: yes

- name: download NodeJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: copy Backend service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service


- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.sheshudevops.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: Start Backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes
    daemon_reload: yes